### ISSUE TITLE
Change pizza_cart and drink_cart

### ISSUE THREAD

**Issue by Framinus** [Framinus/pizza-restaurant#4]
instead of having these two tables, we can put a cart_id directly on the pizza table.

**Comment by Framinus** [comment]
I can work on this one! Let me know if this interferes with any schema changes. I'll push up my changes as a branch and not merge it until we figure that out!

**Comment by Framinus** [comment]
I realized that we can get rid of pizza cart by assigning a cart_id to pizza, but we run into a problem trying to get rid of the drinks_cart table - since we are not assembling a drink, there isn't that extra level of abstraction, and the only other table associated with drink is the base drinks table, and we don't want to assign a cart_id to that. maybe we just leave the drinks_cart table for now...

**Comment by Framinus** [comment]
Solution is on the issue4 branch.

**Comment by alexandrawaite** [comment]
I see what you mean about the drink_cart table. I think this solution works great!
